# Copyright (C) 2026 Roessling Digital Solutions LLC
# SPDX-License-Identifier: AGPL-3.0-or-later
# Additional terms under AGPL section 7 apply: see LICENSE-ADDITIONAL-TERMS.md

"""The record: one file per explained change, never edited after it merges.

    python docs/record/tools/record.py                     # rewrite docs/record/README.md
    python docs/record/tools/record.py check               # names, numbers, citations
    python docs/record/tools/record.py check --base REF    # and no existing item changed since REF
    python docs/record/tools/record.py index               # print every item, numbered and new
    python docs/record/tools/record.py new "A title"       # create today's file for a new item

`docs/record/README.md` is generated by this script; a clean re-run rewrites it byte
for byte, which is how CI checks that nobody edited it by hand.

Until 2026-09-16 every item lived in `ARCHITECTURE.md` §10 under a number, and two
changes filed on the same day took the same next number. Numbered items 1 to 136 and
96A keep their numbers so the citations of them still resolve; a new item has no
number, only a date and a subject.
"""

import datetime
import re
import subprocess
import sys
from pathlib import Path

RECORD = Path(__file__).resolve().parents[1]
ROOT = RECORD.parents[1]
README = RECORD / "README.md"

DATE_DIR = re.compile(r"^\d{4}-\d{2}-\d{2}$")
NUMBERED = re.compile(r"^(\d{3})([a-z]?)\.md$")
SUBJECT = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
LAST_NUMBERED_DATE = "2026-09-15"
NUMBERED_SET = {(n, "") for n in range(1, 137)} | {(96, "a")}
SECTION_NOTES = {"2026-09-06/section-note.md"}

# "§10 item 19", "§10 items 52 and 53", "§10, item 4", "§10 resolved item 4",
# "`ARCHITECTURE.md` item 103", "§10 items 103, 104 and 111".
# A number followed by "-dd" is a date ("item 106, 2026-09-08"), not a second item.
_NUM = r"\d+[A-Za-z]?\b(?!-\d)"
CITATION = re.compile(
    r"(?:§10,?\s+(?:resolved\s+)?|ARCHITECTURE\.md`?\s+(?:§10,?\s+)?)items?\s+"
    rf"({_NUM}(?:(?:\s*,\s*(?:and\s+)?|\s+and\s+){_NUM})*)"
)
CITED_SUFFIXES = {".rs", ".md", ".py", ".yaml", ".yml", ".toml"}
SKIP_DIRS = {"target", ".git", "node_modules"}


def items():
    """Every item file as (date, name, path), in date then name order."""
    out = []
    for d in sorted(p for p in RECORD.iterdir() if p.is_dir() and p.name != "tools"):
        for f in sorted(d.iterdir()):
            out.append((d.name, f.name, f))
    return out


def numbered():
    """{(number, suffix): (date, path)} for the numbered items."""
    found = {}
    for date, name, path in items():
        m = NUMBERED.match(name)
        if m:
            found[(int(m.group(1)), m.group(2))] = (date, path)
    return found


def title(path):
    first = path.read_text(encoding="utf-8").split("\n", 1)[0]
    return first[2:].strip() if first.startswith("# ") else ""


def opening(path, width=88):
    """The first sentence-ish of an item's body, as plain text for a table cell."""
    lines = path.read_text(encoding="utf-8").split("\n")
    # Skip the title, the blank line, and the provenance paragraph the move added.
    try:
        start = lines.index("", 2) + 1
    except ValueError:
        start = 1
    words = " ".join(l.strip() for l in lines[start:] if l.strip()).split()
    text = re.sub(r"[`*]", "", " ".join(words)).replace("|", "/")
    if len(text) <= width:
        return text
    cut = text[:width].rsplit(" ", 1)[0]
    return cut.rstrip(",;:") + " ..."


def render_readme():
    L = [
        "# The record",
        "",
        "One file per change that needed explaining, written when the change was made and",
        "not edited afterwards. Until 2026-09-16 these items were `ARCHITECTURE.md` §10;",
        "they moved here with their wording unchanged. This file is generated by",
        "`tools/record.py`; edit the script, not this page.",
        "",
        "## The rules",
        "",
        "- **An item is never edited once it has merged.** A correction is a new item that",
        "  names the one it corrects. `record.py check --base` fails a pull request that",
        "  modifies, renames or deletes an existing item.",
        "- **A new item is `<YYYY-MM-DD>/<subject>.md`**: the date of the change and a short",
        "  lower-case hyphenated subject, opening with a `# ` title. It has no number, so",
        "  two changes filed on the same day cannot take the same one.",
        "- **Items 1 to 136 and 96A keep their numbers** as `<date>/NNN.md`, so every",
        "  citation of \"§10 item N\" in the code and documents still names one file.",
        "  `record.py check` resolves each of those citations.",
        "- **An item explains; it does not hold the present.** What is true now is read",
        "  from sources that are generated or checked: [`../unbuilt.md`](../unbuilt.md),",
        "  [`../signatures.md`](../signatures.md), the gap register and decision ledger in",
        "  [`../mission/gap-analysis/`](../mission/gap-analysis/README.md), the verification",
        "  table, and the crate manifests.",
        "",
        "## Commands",
        "",
        "```bash",
        "python docs/record/tools/record.py new \"The subject of the change\"",
        "```",
        "",
        "```bash",
        "python docs/record/tools/record.py check --base origin/main",
        "```",
        "",
        "```bash",
        "python docs/record/tools/record.py index",
        "```",
        "",
        "Items filed after 2026-09-16 are listed by their date directories; `index` prints",
        "them together with the numbered ones.",
        "",
        "## Items 1 to 136 and 96A",
        "",
        "| Item | Date heading | File | Opens with |",
        "|---|---|---|---|",
    ]
    found = numbered()
    for (n, suf) in sorted(found):
        date, path = found[(n, suf)]
        rel = path.relative_to(RECORD).as_posix()
        L.append(f"| {n}{suf.upper()} | {date} | [{rel}]({rel}) | {opening(path)} |")
    notes = [(d, p) for d, name, p in items() if f"{d}/{name}" in SECTION_NOTES]
    if notes:
        L += ["", "## Notes that opened a date heading", ""]
        for date, path in notes:
            rel = path.relative_to(RECORD).as_posix()
            L.append(f"- [{rel}]({rel}): {opening(path)}")
    return "\n".join(L) + "\n"


def citations():
    """Every numbered-item citation outside the record's own README, as (file, line, label)."""
    out = []
    for path in ROOT.rglob("*"):
        if path.suffix not in CITED_SUFFIXES or not path.is_file():
            continue
        rel = path.relative_to(ROOT)
        if SKIP_DIRS.intersection(rel.parts) or path == README:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in CITATION.finditer(text):
            line = text.count("\n", 0, m.start()) + 1
            for label in re.findall(_NUM, m.group(1)):
                out.append((rel.as_posix(), line, label))
    return out


def check(base=None):
    problems = []
    for p in RECORD.iterdir():
        if p.is_file() and p.name != "README.md":
            problems.append(f"{p.name}: only README.md sits at the top of docs/record")
        if p.is_dir() and p.name != "tools" and not DATE_DIR.match(p.name):
            problems.append(f"{p.name}/: a record directory is named YYYY-MM-DD")
    found = {}
    for date, name, path in items():
        where = f"{date}/{name}"
        if not path.is_file() or path.suffix != ".md":
            problems.append(f"{where}: an item is a Markdown file")
            continue
        m = NUMBERED.match(name)
        if m:
            key = (int(m.group(1)), m.group(2))
            if date > LAST_NUMBERED_DATE:
                problems.append(f"{where}: new items are named by subject, not by number")
            if key in found:
                problems.append(f"{where}: item {key} also at {found[key]}")
            found[key] = where
        elif where not in SECTION_NOTES and not SUBJECT.match(name):
            problems.append(f"{where}: name a new item <lower-case-subject>.md")
        if not title(path):
            problems.append(f"{where}: an item opens with a '# ' title")
    missing = NUMBERED_SET - set(found)
    extra = set(found) - NUMBERED_SET
    if missing:
        problems.append(f"numbered items missing: {sorted(missing)}")
    if extra:
        problems.append(f"numbered items that never existed: {sorted(extra)}")
    labels = {f"{n}{s}" for n, s in NUMBERED_SET}
    cited = citations()
    for rel, line, label in cited:
        if label.lower() not in labels:
            problems.append(f"{rel}:{line}: cites §10 item {label}, which does not exist")
    if base:
        diff = subprocess.run(
            ["git", "diff", "--name-status", "--diff-filter=DMRT", f"{base}...HEAD", "--",
             RECORD.relative_to(ROOT).as_posix()],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout
        for row in diff.splitlines():
            paths = row.split("\t")[1:]
            if all(p.endswith("docs/record/README.md") or "/tools/" in p for p in paths):
                continue
            problems.append(f"an existing item changed since {base}: {row}")
    if README.read_text(encoding="utf-8") != render_readme():
        problems.append("README.md is stale or hand-edited: run python docs/record/tools/record.py")
    return problems, len(cited)


def main(argv):
    cmd = argv[1] if len(argv) > 1 else "build"
    if cmd == "build":
        README.write_text(render_readme(), encoding="utf-8", newline="\n")
        return 0
    if cmd == "check":
        base = argv[argv.index("--base") + 1] if "--base" in argv else None
        problems, n = check(base)
        for p in problems:
            print(f"record: {p}")
        print(f"record check: {len(problems)} problems, {n} numbered-item citations resolved")
        return 1 if problems else 0
    if cmd == "index":
        for date, name, path in items():
            print(f"{date}/{name}\t{title(path)}")
        return 0
    if cmd == "new" and len(argv) > 2:
        words = re.findall(r"[a-z0-9]+", argv[2].lower())
        today = datetime.date.today().isoformat()
        path = RECORD / today / ("-".join(words[:8]) + ".md")
        if path.exists():
            print(f"{path.relative_to(ROOT).as_posix()} exists; choose another subject")
            return 1
        path.parent.mkdir(exist_ok=True)
        path.write_text(f"# {argv[2]}\n\n", encoding="utf-8", newline="\n")
        print(path.relative_to(ROOT).as_posix())
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
