' Generated by tools/export_ea_script.py -- builds the Gungnir UAF model
' directly via EA's Automation interface, reading bulk data from the four CSV
' files this generator wrote alongside this script. Re-running duplicates
' everything; delete the "Gungnir UAF Model" package first for a clean rebuild.

' >>> EDIT THIS to the folder holding the four gungnir-uaf-*.csv files <<<
Const DATA_DIR = "C:\path\to\folder\containing\the\csv\files"

Dim repo, fso, rootPkg, elementIds, connectorIds, packagesByTitle, n

Function ParseCSVLine(line)
  Dim fields(), fieldCount, i, ch, cur, inQuotes
  ReDim fields(255)
  fieldCount = 0
  cur = ""
  inQuotes = False
  i = 1
  Do While i <= Len(line)
    ch = Mid(line, i, 1)
    If inQuotes Then
      If ch = """" Then
        If i < Len(line) And Mid(line, i + 1, 1) = """" Then
          cur = cur & """"
          i = i + 1
        Else
          inQuotes = False
        End If
      Else
        cur = cur & ch
      End If
    Else
      If ch = """" Then
        inQuotes = True
      ElseIf ch = "," Then
        fields(fieldCount) = cur
        fieldCount = fieldCount + 1
        cur = ""
      Else
        cur = cur & ch
      End If
    End If
    i = i + 1
  Loop
  fields(fieldCount) = cur
  fieldCount = fieldCount + 1
  ReDim Preserve fields(fieldCount - 1)
  ParseCSVLine = fields
End Function

Function IsHex4(s)
  Dim i, c
  IsHex4 = (Len(s) = 4)
  If Not IsHex4 Then Exit Function
  For i = 1 To 4
    c = UCase(Mid(s, i, 1))
    If InStr("0123456789ABCDEF", c) = 0 Then
      IsHex4 = False
      Exit Function
    End If
  Next
End Function

' A plain character scan, not RegExp: a regex "\\u([0-9A-Fa-f]{4})" pattern
' written as a VBScript string literal (which does not itself interpret
' backslashes) matched "u00a7" without the leading backslash -- verified by
' checking the match's FirstIndex/Length directly, not by eyeballing console
' output (WScript.Echo of a non-ASCII character renders as nothing under
' cscript's console codepage, which looks like -- but is not -- a dropped
' character; Len() and AscW() on the actual string values are what settled it).
Function DecodeUnicodeEscapes(s)
  Dim result, pos, bs, hex4
  bs = Chr(92)
  result = ""
  pos = 1
  Do While pos <= Len(s)
    If Mid(s, pos, 1) = bs And Mid(s, pos + 1, 1) = "u" And IsHex4(Mid(s, pos + 2, 4)) Then
      hex4 = Mid(s, pos + 2, 4)
      result = result & ChrW(CLng("&H" & hex4))
      pos = pos + 6
    Else
      result = result & Mid(s, pos, 1)
      pos = pos + 1
    End If
  Loop
  DecodeUnicodeEscapes = result
End Function

Function ReadCSVRows(path)
  Dim f, allLines, rows, i, fields
  Set f = fso.OpenTextFile(path, 1, False, 0)
  allLines = Split(f.ReadAll(), vbLf)
  f.Close
  ReDim rows(UBound(allLines))
  Dim rowCount
  rowCount = 0
  For i = 1 To UBound(allLines)  ' skip header row (index 0)
    If Len(Trim(allLines(i))) > 0 Then
      fields = ParseCSVLine(allLines(i))
      Dim j
      For j = 0 To UBound(fields)
        fields(j) = DecodeUnicodeEscapes(fields(j))
      Next
      rows(rowCount) = fields
      rowCount = rowCount + 1
    End If
  Next
  ReDim Preserve rows(rowCount - 1)
  ReadCSVRows = rows
End Function

Function GetOrCreatePackage(parentPackages, pkgName)
  If packagesByTitle.Exists(pkgName) Then
    Set GetOrCreatePackage = packagesByTitle.Item(pkgName)
    Exit Function
  End If
  Dim newP
  Set newP = parentPackages.AddNew(pkgName, "Package")
  newP.Update
  parentPackages.Refresh
  packagesByTitle.Add pkgName, newP
  Set GetOrCreatePackage = newP
End Function

Function AddTag(owner, tagName, tagValue)
  Dim t
  Set t = owner.TaggedValues.AddNew(tagName, tagValue)
  t.Update
End Function

Set repo = Repository
Set fso = CreateObject("Scripting.FileSystemObject")
Set elementIds = CreateObject("Scripting.Dictionary")
Set connectorIds = CreateObject("Scripting.Dictionary")
Set packagesByTitle = CreateObject("Scripting.Dictionary")

repo.EnableCache = True
repo.EnableUIUpdates = False
Set rootPkg = GetOrCreatePackage(repo.Models, "Gungnir UAF Model")

' ---- elements ----
Dim elRows, elRow, sectionPkg, el
elRows = ReadCSVRows(DATA_DIR & "\gungnir-uaf-elements.csv")
n = 0
For Each elRow In elRows
  ' elRow: id, section, stereotype, name, description
  Set sectionPkg = GetOrCreatePackage(rootPkg.Packages, elRow(1))
  Set el = sectionPkg.Elements.AddNew(elRow(3), "Class")
  el.Stereotype = elRow(2)
  If Len(elRow(4)) > 0 Then el.Notes = elRow(4)
  el.Update
  elementIds.Add elRow(0), el.ElementID
  n = n + 1
  If n Mod 50 = 0 Then Session.Output "  " & n & " elements created"
Next
Session.Output n & " elements created total."

' ---- element tags ----
Dim tagRows, tagRow
tagRows = ReadCSVRows(DATA_DIR & "\gungnir-uaf-element-tags.csv")
For Each tagRow In tagRows
  ' tagRow: id, key, value
  If elementIds.Exists(tagRow(0)) Then
    AddTag repo.GetElementByID(elementIds.Item(tagRow(0))), tagRow(1), tagRow(2)
  End If
Next
Session.Output "element tags applied."

' ---- relationships ----
Dim relRows, relRow, fromEl, conn
relRows = ReadCSVRows(DATA_DIR & "\gungnir-uaf-relationships.csv")
n = 0
For Each relRow In relRows
  ' relRow: rel_id, kind, stereotype, from_id, to_id, name
  If elementIds.Exists(relRow(3)) And elementIds.Exists(relRow(4)) Then
    Set fromEl = repo.GetElementByID(elementIds.Item(relRow(3)))
    Set conn = fromEl.Connectors.AddNew(relRow(5), "Dependency")
    conn.SupplierID = elementIds.Item(relRow(4))
    conn.Stereotype = relRow(2)
    conn.Update
    fromEl.Connectors.Refresh
    connectorIds.Add relRow(0), conn.ConnectorID
    n = n + 1
    If n Mod 100 = 0 Then Session.Output "  " & n & " relationships created"
  End If
Next
Session.Output n & " relationships created total."

' ---- relationship tags ----
Dim relTagRows, relTagRow
relTagRows = ReadCSVRows(DATA_DIR & "\gungnir-uaf-relationship-tags.csv")
For Each relTagRow In relTagRows
  ' relTagRow: rel_id, key, value
  If connectorIds.Exists(relTagRow(0)) Then
    AddTag repo.GetConnectorByID(connectorIds.Item(relTagRow(0))), relTagRow(1), relTagRow(2)
  End If
Next
Session.Output "relationship tags applied."

repo.EnableUIUpdates = True
MsgBox "Done. Reopen the Gungnir UAF Model package (or press F5) if the Project Browser doesn't show it yet."
