# Copyright (C) 2026 Roessling Digital Solutions LLC
# SPDX-License-Identifier: AGPL-3.0-or-later
# Additional terms under AGPL section 7 apply: see LICENSE-ADDITIONAL-TERMS.md

"""Generate the plan 05 gap-analysis deliverables from one data set.

`gap-register.md`, `coverage-matrix.md`, `technical-gap-map.md`,
`closure-roadmap.md`, and `decisions-needed.md` in this folder are **generated by
this script** from the YAML under `../data/`: `gaps.yaml`, `decisions.yaml` and
`design-coverage.yaml`. Editing a generated document by hand is reverted the next time
this runs; edit the data and re-run instead.

    python docs/mission/gap-analysis/tools/gen_gaps.py
    python docs/mission/gap-analysis/tools/gen_gaps.py --base origin/main

The second form also refuses a change that edits or removes history merged on the
base: a gap's status is the status of its last history entry, so rewriting an old
entry would rewrite what the register said at the time.

The other inputs are the plan 04 capability documents in `../../capabilities/`. The
script is deterministic: with the same inputs it rewrites the five documents byte for
byte, so a clean re-run is also the check that a hand edit has not crept in.

Lives in the repository rather than in a session scratchpad so that the next change
to the register can find it -- CLAUDE.md tells whoever edits the register to prefer
the generator over the table.
"""

import datetime
import re
import subprocess
import sys
from pathlib import Path

import yaml

# .../docs/mission/gap-analysis/tools/gen_gaps.py -> .../docs
ROOT = Path(__file__).resolve().parents[3]
CAPS_DIR = ROOT / "mission" / "capabilities"
OUT = ROOT / "mission" / "gap-analysis"
DATE = "2026-09-04"

# ---------------------------------------------------------------- inputs
tax = (CAPS_DIR / "capability-taxonomy.md").read_text(encoding="utf-8")
cap_names = {}
for m in re.finditer(r"^\| (CAP-\d\.\d+) \| (.+?) \|$", tax, re.M):
    cap_names[m.group(1)] = m.group(2)

thread_rows = (CAPS_DIR / "capability-to-thread-matrix.md").read_text(encoding="utf-8")
reach = {}
for line in thread_rows.splitlines():
    m = re.match(r"^\| (CAP-\d\.\d+) [^|]*\|(.*)\|$", line)
    if m:
        cells = [c.strip() for c in m.group(2).split("|")]
        reach[m.group(1)] = sum(1 for c in cells if c)

crate_rows = (CAPS_DIR / "capability-to-crate-matrix.md").read_text(encoding="utf-8")
impl_cov = {}
for line in crate_rows.splitlines():
    m = re.match(r"^\| (CAP-\d\.\d+) [^|]*\| (.*?) \| (\w+)", line)
    if m:
        impl_cov[m.group(1)] = m.group(3)

short = {}
for line in thread_rows.splitlines():
    m = re.match(r"^\| (CAP-\d\.\d+) (.+?) \|", line)
    if m:
        short[m.group(1)] = m.group(2).strip()

# ---------------------------------------------------------------- data
# The gaps, the decisions and the design coverage are YAML under `../data/`. They lived
# in this file as Python literals until 2026-09-16, where a status column and the prose
# beside it drifted apart often enough to be a recorded failure mode; now a gap has no
# status field at all, only a history whose last entry is the status.
DATA = OUT / "data"
DATA_REL = "docs/mission/gap-analysis/data"
REPO = ROOT.parent
STATUSES = ("Open", "Planned", "In progress", "Closed")
DESIGN_COVERAGE = ("full", "partial", "none", "planned")
GAP_FIELDS = ("id", "name", "type", "caps", "layer", "sev", "effort", "target", "owner",
              "deps", "impact", "evidence", "action", "ref", "history")
DECISION_FIELDS = ("id", "decision", "question", "raised_in", "decider", "unblocks",
                   "resolved", "amended", "outcome")
# A history note written after the data left this file is short: the explanation belongs
# in a `docs/record/` item or a pull request, and the note links it.
MIGRATED = "2026-09-16"
NOTE_WORDS = 120
_ISO = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def _iso(v):
    return v.isoformat() if isinstance(v, (datetime.date, datetime.datetime)) else v


def _entries(name, text):
    raw = yaml.safe_load(text)
    if not isinstance(raw, list) or not all(isinstance(e, dict) for e in raw):
        raise SystemExit(f"{DATA_REL}/{name}: expected a list of mappings")
    return raw


def _load_gaps(text):
    gaps, problems = [], []
    for e in _entries("gaps.yaml", text):
        gid = e.get("id", "?")
        if "status" in e:
            problems.append(f"{gid}: a gap has no status field; append a history entry instead")
        if "desc" in e:
            problems.append(f"{gid}: a gap has no desc field; its history notes carry the narrative")
        extra = sorted(set(e) - set(GAP_FIELDS) - {"status", "desc"})
        missing = [k for k in GAP_FIELDS if k not in e]
        if extra or missing:
            problems.append(f"{gid}: unknown fields {extra}, missing fields {missing}")
            continue
        g = dict(e)
        g["ref"] = g["ref"] or ""
        g["history"] = [{k: _iso(v) for k, v in h.items()} for h in (e["history"] or [])]
        if not g["history"]:
            problems.append(f"{gid}: history is empty; a gap starts with one entry")
            continue
        last = None
        for i, h in enumerate(g["history"]):
            where = f"{gid} history[{i}]"
            if set(h) != {"date", "status", "note"}:
                problems.append(f"{where}: an entry has exactly date, status and note")
                continue
            if not (isinstance(h["date"], str) and _ISO.match(h["date"])):
                problems.append(f"{where}: date is YYYY-MM-DD")
            elif last and h["date"] < last:
                problems.append(f"{where}: dates run oldest first; {h['date']} follows {last}")
            else:
                last = h["date"]
            if h["status"] not in STATUSES:
                problems.append(f"{where}: status is one of {', '.join(STATUSES)}")
            if not isinstance(h["note"], str) or not h["note"].strip():
                problems.append(f"{where}: a note says what changed")
            elif h["date"] > MIGRATED and len(h["note"].split()) > NOTE_WORDS:
                problems.append(f"{where}: {len(h['note'].split())} words; keep a note to "
                                f"{NOTE_WORDS} and link a docs/record item for the rest")
        if g["type"] not in ("Mission", "Technical"):
            problems.append(f"{gid}: type is Mission or Technical")
        if g["effort"] not in ("S", "M", "L", "XL"):
            problems.append(f"{gid}: effort is S, M, L or XL")
        if not (isinstance(g["sev"], int) and 1 <= g["sev"] <= 5):
            problems.append(f"{gid}: sev is 1 to 5")
        g["status"] = g["history"][-1]["status"]
        gaps.append(g)
    return gaps, problems


def _load_decisions(text):
    decs, problems = [], []
    for e in _entries("decisions.yaml", text):
        did = e.get("id", "?")
        extra = sorted(set(e) - set(DECISION_FIELDS))
        missing = [k for k in DECISION_FIELDS if k not in e and k not in ("resolved", "amended")]
        if extra or missing:
            problems.append(f"{did}: unknown fields {extra}, missing fields {missing}")
            continue
        d = dict(e)
        d["resolved"] = _iso(d.get("resolved"))
        d["amended"] = [_iso(x) for x in (d.get("amended") or [])]
        if d["resolved"] is not None and not _ISO.match(str(d["resolved"])):
            problems.append(f"{did}: resolved is YYYY-MM-DD")
        if d["amended"] and d["resolved"] is None:
            problems.append(f"{did}: an open decision has no amendments")
        if d["amended"] != sorted(d["amended"]) or (d["amended"] and d["resolved"] and d["amended"][0] < d["resolved"]):
            problems.append(f"{did}: amendment dates run oldest first and follow the resolution")
        if d["resolved"] is None:
            d["status"] = "Open"
        else:
            d["status"] = f"Resolved {d['resolved']}"
            if d["amended"]:
                dates = d["amended"]
                joined = dates[0] if len(dates) == 1 else ", ".join(dates[:-1]) + " and " + dates[-1]
                d["status"] += f", amended {joined}"
        d["outcome"] = d.get("outcome") or ""
        decs.append(d)
    return decs, problems


def _git_show(ref, name):
    r = subprocess.run(["git", "show", f"{ref}:{DATA_REL}/{name}"], cwd=REPO,
                       capture_output=True, text=True, encoding="utf-8")
    return r.stdout if r.returncode == 0 else None


def _append_only(ref, gaps, decs):
    """Merged history is never rewritten: each base entry survives unchanged in HEAD."""
    problems = []
    base_gaps_text = _git_show(ref, "gaps.yaml")
    if base_gaps_text is not None:
        base_gaps, _ = _load_gaps(base_gaps_text)
        head = {g["id"]: g for g in gaps}
        for b in base_gaps:
            h = head.get(b["id"])
            if h is None:
                problems.append(f"{b['id']}: removed; gap ids are never removed or reused")
                continue
            n = len(b["history"])
            if h["history"][:n] != b["history"]:
                problems.append(f"{b['id']}: a history entry merged on {ref} was edited or removed")
            for i, e in enumerate(h["history"][n:], start=n):
                # An entry dated after MIGRATED was already held to the limit on load.
                if e["date"] <= MIGRATED and len(e["note"].split()) > NOTE_WORDS:
                    problems.append(f"{b['id']} history[{i}]: new notes are at most {NOTE_WORDS} words")
        base_ids = {b["id"] for b in base_gaps}
        for g in gaps:
            if g["id"] not in base_ids:
                for i, e in enumerate(g["history"]):
                    if e["date"] <= MIGRATED and len(e["note"].split()) > NOTE_WORDS:
                        problems.append(f"{g['id']} history[{i}]: new notes are at most {NOTE_WORDS} words")
    base_dec_text = _git_show(ref, "decisions.yaml")
    if base_dec_text is not None:
        base_decs, _ = _load_decisions(base_dec_text)
        head = {d["id"]: d for d in decs}
        for b in base_decs:
            h = head.get(b["id"])
            if h is None:
                problems.append(f"{b['id']}: removed; decision ids are never removed or reused")
                continue
            if b["resolved"] is not None and h["resolved"] != b["resolved"]:
                problems.append(f"{b['id']}: its resolution date merged on {ref} changed")
            if h["amended"][: len(b["amended"])] != b["amended"]:
                problems.append(f"{b['id']}: an amendment date merged on {ref} changed")
    return problems


G, _gap_problems = _load_gaps((DATA / "gaps.yaml").read_text(encoding="utf-8"))
_decs, _dec_problems = _load_decisions((DATA / "decisions.yaml").read_text(encoding="utf-8"))
_cov = _entries("design-coverage.yaml", (DATA / "design-coverage.yaml").read_text(encoding="utf-8"))
_cov_problems = [f"{c.get('capability')}: design is one of {', '.join(DESIGN_COVERAGE)}"
                 for c in _cov if c.get("design") not in DESIGN_COVERAGE]
_problems = _gap_problems + _dec_problems + _cov_problems
if "--base" in sys.argv:
    _problems += _append_only(sys.argv[sys.argv.index("--base") + 1], G, _decs)
if _problems:
    raise SystemExit("gap-analysis data:\n  " + "\n  ".join(_problems))

design = {c["capability"]: (c["design"], c["evidence"]) for c in _cov}
decisions = [(d["id"], d["decision"], d["question"], d["raised_in"], d["decider"], d["unblocks"])
             for d in _decs]
outcomes = {d["id"]: (d["status"], d["outcome"]) for d in _decs}


def narrative(g):
    """Every history note of a gap, oldest first, as one paragraph."""
    return " ".join(h["note"] for h in g["history"])


def history_lines(g):
    out = ["- History:"]
    for h in g["history"]:
        lines = h["note"].split("\n")
        body = lines[0] + "".join("\n" + ("    " + l if l else "") for l in lines[1:])
        out.append(f"  - {h['date']}, {h['status']}: {body}")
    return out


# ---------------------------------------------------------------- derived

import re as _re
_REL = [
 (r"`gungnir-capabilities\.md", "`../../gungnir-capabilities.md"),
 (r"`verification-capability-table\.md", "`../../verification-capability-table.md"),
 (r"`performance-budgets\.md", "`../../performance-budgets.md"),
 (r"`release-governance\.md", "`../../release-governance.md"),
 (r"`gungnir-api-v1\.md", "`../../gungnir-api-v1.md"),
 (r"`architecture\.md", "`../../architecture.md"),
 (r"`ARCHITECTURE\.md", "`../../../ARCHITECTURE.md"),
 (r"`CONTRIBUTING\.md", "`../../../CONTRIBUTING.md"),
 (r"`docs/design/", "`../../design/"),
 (r"`docs/plans/", "`../../plans/"),
 (r"`docs/ux/", "`../../ux/"),
 (r"`rust-ui-tech-stack-summary\.md", "`../../rust-ui-tech-stack-summary.md"),
 (r"`mission/capabilities/", "`../capabilities/"),
 (r"`mission/", "`../"),
 (r"`mission-analysis\.md", "`../mission-analysis.md"),
]
def rel(t):
    for a, b in _REL:
        t = _re.sub(a, b, t)
    return t
for _g in G:
    for _k in ("evidence", "impact", "action", "ref"):
        _g[_k] = rel(_g[_k])
    for _h in _g["history"]:
        _h["note"] = rel(_h["note"])
decisions = [tuple(rel(x) for x in d) for d in decisions]
EFFORT_RANK = {"S": 1, "M": 2, "L": 3, "XL": 4}
for g in G:
    g["reach"] = max(reach[c] for c in g["caps"])
    g["priority"] = g["sev"] * g["reach"]
# Identifiers must be unique. `README.md` under "Identifiers": "`GAP-nnn`: a gap.
# Stable; never reused. New gaps are appended." -- and `D-nn` is stable likewise. Two
# branches that each append a gap pick the same next number, and git merges them with no
# conflict, because the two `gap(...)` calls sit at different offsets. Nothing below
# catches that: the dependency, cycle, ordering and coverage checks all read `ids` and
# `dids` as sets, which collapse a duplicate, so the register renders two summary rows
# and two entry blocks under the one identifier -- and CI's regenerate-and-diff still
# passes, because the generator stays deterministic. It is not reliably loud either: two
# duplicates in the same target increment do starve `closure-roadmap.md`'s wave below
# into a bare `IndexError`, but only after three of the five documents are written, while
# two in different increments write all five and exit 0. So count the ids here, before
# they are collected. Four collisions so far: GAP-090 (and again on the GAP-094 it was
# renumbered to), GAP-097, and GAP-102 on 2026-09-09.
def dupes(seq):
    seen, dup = set(), []
    for x in seq:
        if x in seen and x not in dup:
            dup.append(x)
        seen.add(x)
    return dup
_dup = dupes([g["id"] for g in G])
if _dup:
    raise SystemExit(f"duplicate gap id: {', '.join(_dup)}; ids are never reused (README.md)")
_dup = dupes([d[0] for d in decisions])
if _dup:
    raise SystemExit(f"duplicate decision id: {', '.join(_dup)}; ids are never reused (README.md)")

ids = {g["id"] for g in G}
dids = {d[0] for d in decisions}
# Every decision has an outcome and every outcome has a decision. `decisions-needed.md`
# reads `outcomes[d[0]]` twice, so a decision with no outcome is a loud `KeyError` there,
# but an outcome left behind by a deleted decision renders nothing and would pass.
_no_outcome = sorted(dids - set(outcomes))
_no_decision = sorted(set(outcomes) - dids)
if _no_outcome or _no_decision:
    raise SystemExit(f"decision ids with no outcome: {_no_outcome}; "
                     f"outcome ids with no decision: {_no_decision}")
for g in G:
    for d in g["deps"]:
        assert d in ids or d in dids, (g["id"], d)
# cycle check
adj = {g["id"]: [d for d in g["deps"] if d in ids] for g in G}
state = {}
def visit(n, stack):
    if state.get(n) == 1:
        raise SystemExit(f"cycle: {stack + [n]}")
    if state.get(n) == 2:
        return
    state[n] = 1
    for m in adj[n]:
        visit(m, stack + [n])
    state[n] = 2
for n in adj:
    visit(n, [])
# targets must not precede deps' targets
order = {"I1": 1, "I2": 2, "I3": 3, "I4": 4}
byid = {g["id"]: g for g in G}
for g in G:
    for d in adj[g["id"]]:
        assert order[byid[d]["target"]] <= order[g["target"]], (g["id"], d)

caps_with_gaps = {}
for g in G:
    for c in g["caps"]:
        caps_with_gaps.setdefault(c, []).append(g["id"])
for c, (dc, _) in design.items():
    if (dc != "full" or impl_cov[c] != "full") and c not in caps_with_gaps:
        raise SystemExit(f"{c} has coverage {dc}/{impl_cov[c]} but no gap")

GENERATED = ("Generated by `tools/gen_gaps.py` from `data/`: edit the data and re-run the "
             "generator, never this file.\n")


def caplink(c):
    return f"{c} {short[c]}"

# ---------------------------------------------------------------- gap-register.md
L = []
L.append("# Gap register\n")
L.append(f"Status: first draft, {DATE}. One entry per gap between what the missions need\n"
         "(`../capabilities/`) and what Gungnir is designed and built to provide. The scoring\n"
         "scheme and the maintenance rule are in `README.md`; the decisions that gaps depend\n"
         "on are in `decisions-needed.md`. Severity, effort, and target values are the\n"
         "drafting agent's proposals for the owner and the engineering reviewer to confirm.\n")
L.append(GENERATED.rstrip("\n") + " A gap's status is the status of the last entry in its\n"
         "history, and an entry is never edited once it has merged.\n")
L.append("## Summary\n")
L.append("| Id | Gap | Type | Capability | Sev | Reach | Effort | Priority | Target | Owner | Status |")
L.append("|---|---|---|---|---|---|---|---|---|---|---|")
for g in G:
    L.append(f"| {g['id']} | {g['name']} | {g['type']} | {', '.join(g['caps'])} | {g['sev']} | {g['reach']} | {g['effort']} | {g['priority']} | {g['target']} | {g['owner']} | {g['status']} |")
n_m = sum(1 for g in G if g["type"] == "Mission"); n_t = sum(1 for g in G if g["type"] == "Technical")
L.append(f"\nCounts: {len(G)} gaps, {n_m} mission, {n_t} technical; {sum(1 for g in G if g['status']=='Planned')} already covered by a plan in `../../plans/`. "
         "Reach is the number of mission threads the capability serves (from\n`../capabilities/capability-to-thread-matrix.md`); priority is severity times reach.\n")
L.append("## Entries\n")
for g in G:
    L.append(f"**{g['id']} {g['name']}**"); L.append("")
    L.append(f"- Type: {g['type']}.")
    L.append("- Capability: " + "; ".join(caplink(c) for c in g["caps"]) + ".")
    L.extend(history_lines(g))
    L.append(f"- Evidence: {g['evidence']}.")
    L.append(f"- Severity: {g['sev']}. Reach: {g['reach']} threads. Effort: {g['effort']}. Priority: {g['priority']}.")
    L.append(f"- Impact: {g['impact']}")
    L.append(f"- Closing action: {g['action']}")
    L.append(f"- Target: {g['target']}. Owner: {g['owner']}. Status: {g['status']}.")
    if g["ref"]:
        L.append(f"- Reference: {g['ref']}.")
    if g["deps"]:
        L.append("- Depends on: " + ", ".join(g["deps"]) + ".")
    L.append("")
(OUT / "gap-register.md").write_text(rel("\n".join(L)) + "\n", encoding="utf-8", newline="\n")

# ---------------------------------------------------------------- coverage-matrix.md
L = []
L.append("# Coverage matrix\n")
L.append(f"Status: first draft, {DATE}. For each leaf capability: **design coverage** (does the\n"
         "architecture name a component responsible for every part of it: full, partial,\n"
         "none, or planned when a plan in `../../plans/` owns it) and **implementation\n"
         "coverage** (from `../capabilities/capability-to-crate-matrix.md`: full, partial,\n"
         "none), with the evidence and the gaps that follow. A capability with full design\n"
         "coverage and partial implementation has technical gaps only; anything less than\n"
         "full design coverage has at least one mission gap.\n\n"
         "Twenty-two rows reached full design coverage on 2026-09-05 through plan 11's\n"
         "design notes in `../../design/`. That set is reviewed: the engineering reviewer\n"
         "accepted the five new dependency edges, a domain reviewer checked each note against\n"
         "the mission thread step it names, and what the owner signed of it is in\n"
         "`../../signatures.md`. Full design coverage means a reviewed component is named for\n"
         "every part of the capability; implementation is what remains.\n")
L.append(GENERATED)
L.append("| Capability | Design | Implementation | Evidence | Gaps |")
L.append("|---|---|---|---|---|")
for c in cap_names:
    dc, ev = design[c]
    gl = ", ".join(caps_with_gaps.get(c, [])) or "none"
    L.append(f"| {caplink(c)} | {dc} | {impl_cov[c]} | {ev} | {gl} |")
from collections import Counter
dcount = Counter(d[0] for d in design.values()); icount = Counter(impl_cov.values())
L.append("\n## Counts\n")
L.append("| Coverage | Design | Implementation |")
L.append("|---|---|---|")
for k in ["full", "partial", "none", "planned"]:
    L.append(f"| {k} | {dcount.get(k,0)} | {icount.get(k,0)} |")
L.append("\nEvery capability whose design or implementation coverage is less than full has at\n"
         "least one gap entry; the generator refuses to write these documents otherwise.")
(OUT / "coverage-matrix.md").write_text(rel("\n".join(L)) + "\n", encoding="utf-8", newline="\n")

# ---------------------------------------------------------------- technical-gap-map.md
layers = ["Tracking core", "Service facades and wiring", "Productization: sensing and time",
          "Productization: picture and identity", "Productization: decision and policy",
          "Productization: sustainment", "Productization: security", "Deployment and API",
          "UI and data ecosystem", "Verification and governance", "Plans in execution"]
L = []
L.append("# Technical gap map\n")
L.append(f"Status: first draft, {DATE}. The technical gaps from `gap-register.md` grouped by\n"
         "architecture layer (`../../../ARCHITECTURE.md` §1 to §8), each pointing at the\n"
         "record item (`../../record/`, which was `ARCHITECTURE.md` §10) or the\n"
         "`../../verification-capability-table.md` row that tracks it. Mission gaps appear\n"
         "only in the register and the roadmap.\n")
L.append(GENERATED)
L.append("## The §10 open items of 2026-09-04 and the gaps that carried them\n")
L.append("| `ARCHITECTURE.md` §10 open item | Gaps or decisions |")
L.append("|---|---|")
sec10 = [
 ("Scope lock", "D-01"),
 ("The tracking math itself", "GAP-011, GAP-013, GAP-015, GAP-016, GAP-029"),
 ("Intercept geometry", "GAP-031"),
 ("three-d attachment", "GAP-022"),
 ("API transport libraries", "GAP-041, GAP-050"),
 ("Live protocol adapters and industry codecs", "GAP-001, GAP-010, GAP-064"),
 ("Credential mechanism", "D-02, GAP-057"),
 ("Locking the reconciliation and arbitration rules; release-governance items", "D-03, D-10"),
 ("Performance budgets", "D-04, GAP-056"),
 ("Cross-session identity correlation", "GAP-019"),
 ("`uuid` for `GlobalEntityId`", "D-11"),
]
for a, b in sec10:
    L.append(f"| {a} | {b} |")
L.append("\n## By layer\n")
for layer in layers:
    rows = [g for g in G if g["layer"] == layer and g["type"] == "Technical"]
    if not rows:
        continue
    L.append(f"### {layer}\n")
    L.append("| Gap | Capability | Sev | Effort | Target | Tracked in |")
    L.append("|---|---|---|---|---|---|")
    for g in rows:
        ref = g["ref"] or "Added to `ARCHITECTURE.md` §10 by this register"
        L.append(f"| {g['id']} {g['name']} | {', '.join(g['caps'])} | {g['sev']} | {g['effort']} | {g['target']} | {ref} |")
    L.append("")
L.append("## Integration gaps\n")
L.append("Gaps where two components exist but are not connected, found by the coverage pass:\n")
for gid in ["GAP-003", "GAP-014", "GAP-028", "GAP-053", "GAP-059"]:
    g = byid[gid]
    L.append(f"- {gid} {g['name']}: {narrative(g)}")
(OUT / "technical-gap-map.md").write_text(rel("\n".join(L)) + "\n", encoding="utf-8", newline="\n")

# ---------------------------------------------------------------- closure-roadmap.md
L = []
L.append("# Closure roadmap\n")
L.append(f"Status: first draft, {DATE}. Gaps by target increment, ordered by priority\n"
         "(severity times reach) and then by effort, smaller first, so that within an\n"
         "increment the cheapest high-priority closures come first. Dependencies are listed\n"
         "so nothing is scheduled before what it needs; the generator checked that no gap\n"
         "targets an earlier increment than any gap it depends on and that there are no\n"
         "cycles. Increments are those of `../../gungnir-capabilities.md` §7 and the\n"
         "capability roadmap in `../capabilities/capability-roadmap.md`.\n")
L.append(GENERATED)
inc_text = {
 "I2": "Integrate real data. Closes the tracking mathematics, the data path from real sensors, and the harnesses that make everything after it measurable.",
 "I3": "Close the decision loop. Closes the allocator, geometry, asset list, policy model, queue, and the panels that let a human decide in the product.",
 "I4": "Operationalize and scale. Closes the transport and everything that waits on it: peers, handoff, failover, authentication for callers, encryption, releasability.",
}
for inc in ["I2", "I3", "I4"]:
    pool = [g for g in G if g["target"] == inc]
    pool_ids = {g["id"] for g in pool}
    done = set(); rows = []
    while len(rows) < len(pool):
        ready = [g for g in pool if g["id"] not in done and all(d not in pool_ids or d in done for d in g["deps"])]
        ready.sort(key=lambda g: (-g["priority"], EFFORT_RANK[g["effort"]], g["id"]))
        rows.append(ready[0]); done.add(ready[0]["id"])
    L.append(f"## {inc}: {inc_text[inc]}\n")
    L.append("| Order | Gap | Type | Priority | Effort | Owner | Depends on |")
    L.append("|---|---|---|---|---|---|---|")
    for i, g in enumerate(rows, 1):
        L.append(f"| {i} | {g['id']} {g['name']} | {g['type']} | {g['priority']} | {g['effort']} | {g['owner']} | {', '.join(g['deps']) or ''} |")
    L.append("")
L.append("## Critical path (rewritten 2026-09-07, in the development-status review)\n")
L.append("Every gap the previous version of this section named -- GAP-016, GAP-048, GAP-011,\n"
         "GAP-030, GAP-029, GAP-031, GAP-028, GAP-038, GAP-052, GAP-012, GAP-018, GAP-033,\n"
         "GAP-035, GAP-058, GAP-041 -- is Closed, and every decision it named (D-02, D-05,\n"
         "D-08, D-09, D-15, D-16) is Resolved. The path below is traced fresh from the\n"
         "`deps` still open in the register today, not carried forward from the section this\n"
         "replaces.")
L.append("- **GAP-064** (the STANAG 4676 codec; ASTERIX is done) gates **GAP-001** (live sensor\n  adapters, priority 45, the single highest-priority open gap), which gates **GAP-004**\n  (outbound sensor control). GAP-064 also gates **GAP-063** (interface conformance).")
L.append("- **GAP-061** (the self-hosted runner) gates **GAP-093** (Gate 6's threshold\n  enforcement) and is itself waited on by nothing else open.")
L.append("- **GAP-045** (scenario replay through the live pipeline) gates **GAP-087** (PN-16,\n  the planning panel), already in progress on the rest of its scope.")
L.append("- **GAP-023** (data loaders) no longer gates **GAP-024** (GPU point-cloud\n  registration), as of 2026-09-08: GAP-023's remaining item is the DEM half, a\n  projection library that is an owner decision, and the LAS and bounded-COPC readers\n  GAP-024 needs are built and fixture-tested. GAP-024's CPU reference is built and\n  gated, its runner is registered as of the same day, and its §2 verification row\n  uses synthetic clouds, so nothing blocks the WGSL work. **GAP-098** (nothing loads\n  or draws a point cloud) is deliberately not an edge to it: GAP-024 makes the engine\n  correct, GAP-098 makes it reachable, and either can be built first.")
L.append("- **GAP-077**, **GAP-078**, and **GAP-079** (in progress) all feed **GAP-080** (the\n  first two trained models); none of the three has a gap of its own blocking it.")
L.append("- **GAP-067** (this table's own walk) is blocked on nothing: D-16 and D-10, its two\n  named decisions, are both Resolved. It is now purely a matter of the owner's time\n  against 43 rows, not a dependency.")
L.append("\n## Counts\n")
L.append("| Increment | Gaps | Closed / In progress / Open / Planned | Effort S / M / L / XL |")
L.append("|---|---|---|---|")
for inc in ["I2", "I3", "I4"]:
    rows = [g for g in G if g["target"] == inc]
    ec = Counter(g["effort"] for g in rows)
    # A gap's status is its last history entry, so this is how far the increment has
    # got. Generated here so Pj-Rm and the registry can cite it rather than restate it.
    sc = Counter(g["status"] for g in rows)
    L.append(f"| {inc} | {len(rows)} | {sc.get('Closed',0)} / {sc.get('In progress',0)} / "
             f"{sc.get('Open',0)} / {sc.get('Planned',0)} | "
             f"{ec.get('S',0)} / {ec.get('M',0)} / {ec.get('L',0)} / {ec.get('XL',0)} |")
(OUT / "closure-roadmap.md").write_text(rel("\n".join(L)) + "\n", encoding="utf-8", newline="\n")

# ---------------------------------------------------------------- decisions-needed.md
L = []
L.append("# Decisions needed\n")
L.append(f"Status: first draft, {DATE}. Gaps whose closure needs a scoping, policy, or\n"
         "architecture decision from the owner before engineering can start or finish. Each\n"
         "decision lists the gaps it unblocks; the register's entries name the decision in\n"
         "their dependencies. Record the outcome in `data/decisions.yaml`, explain a technical\n"
         "one in a `../../record/` item, and append a history entry to each gap it moves.\n")
L.append(GENERATED)
L.append("| Id | Decision | What is being decided | Where it is raised | Decider | Unblocks | Status |")
L.append("|---|---|---|---|---|---|---|")
for d in decisions:
    L.append("| " + " | ".join(d) + f" | {outcomes[d[0]][0]} |")
L.append("\n## Outcomes\n")
L.append("Recorded with the owner on 2026-09-04, and D-18 and D-19 on 2026-09-05. Technical\n"
         "outcomes are explained in `../../record/`; mission outcomes in `../mission-analysis.md` §11.\n")
L.append("| Id | Outcome |")
L.append("|---|---|")
for d in decisions:
    L.append(f"| {d[0]} {d[1]} | {outcomes[d[0]][1]} |")
L.append("\n## Consequences for the register\n")
L.append("- D-05, D-11, and D-12 created engineering items: GAP-068 (roles in code), GAP-069\n  (`uuid` v7), GAP-070 (display vocabulary).")
L.append("- D-07 moved GAP-036 (fires) from I4 to I3 and put fires deconfliction in the policy\n  model; the fires handoff message is defined in I3 and delivered over the transport\n  with GAP-040 in I4.")
L.append("- D-10 changed GAP-061 from running the GitHub workflows to porting them to GitLab CI\n  on self-hosted runners; effort S to M. **Amended 2026-09-07 to GitHub at\n  `github.com/WayneRoessling/gungnir`**: the port is gone and the eight workflows stay\n  where they are, but the effort stays M, because what gates the gap is not the port. The\n  workspace is not a git repository, so the gap starts with an initial commit, and\n  `gpu-fusion.yml` still needs a self-hosted runner labelled `gpu`. **On 2026-09-07 that\n  workflow was made dormant** (manual dispatch only): with no runner registered, every\n  pull request touching the two crates it watched queued a job that failed a day later,\n  and the job itself ran zero tests, because the GPU path and its tests are GAP-024's\n  and are not built. It now fails a run that executed nothing, so the runner alone\n  cannot pass it.")
L.append("- D-13 fixed the closing action of GAP-021 without a new dependency edge.")
L.append("- D-01 confirms that no gap is out of scope; every I4 item is release content.")
L.append("- Plan 07 (test-track suite, 2026-09-04) delivered the catalogue, class profiles,\n  sensor models, scenario library, reference generator, and ten validated sample sets;\n  GAP-046 moves to In progress and GAP-076 covers the remaining integration.")
L.append("- Plan 06 (UX designs, 2026-09-04) added GAP-071 to GAP-074 (replay, reports, and\n  configuration panels; the status strip; the evidence card, commander summary, and\n  theme additions; the usability test rounds) and raised D-17 (docking and\n  multi-window), resolved the same day.")
L.append("- Plan 09 (ML model integration, 2026-09-04) added GAP-077 to GAP-080: the\n  `gungnir-ml` crate and the inference-runtime sign-off, model manifests as\n  `gungnir-modelops` baselines, the dataset pipeline, and the first two models.")
L.append("- Plan 08 (AI agent integration, 2026-09-04) answered D-14 and kept GAP-044 as the\n  single assistant item; the crate, the providers, the tools, the panel, and the\n  evaluation harness are all inside it.")
L.append("- Plan 11 (design gap closure, 2026-09-05) reviewed the design gaps and applied four\n  corrections: GAP-052 is retyped Mission because nothing is designed; the CAP-6.1\n  coverage row is refreshed now that D-02 is decided; GAP-084 is filed for key custody\n  and GAP-060 narrowed to ciphers; GAP-026 is cross-listed on CAP-5.6.")
L.append("- Plan 11 also closed the design gaps themselves: twenty-two design notes in\n `../../design/` name a component, its types, its edges, its behaviour, and its\n verification row for each. Twenty-three gaps are retyped Mission to Technical\n because they are now designed and awaiting implementation, and twenty-two\n capabilities reach full design coverage. The notes are first drafts awaiting\n the owner and the reviewers.")
L.append("- D-18 (2026-09-05) signed off the API transport stack, the last decision\n  standing between the decided contract and the code, so GAP-041's closing action is now\n  implementation alone. The owner moved GAP-041 from I4 to I2 on 2026-09-05: it carries\n  severity 5 across six mission threads, which is higher than most of I3, and until it\n  exists only the disconnected profile can be exercised and MT-10 cannot run end to end.\n  GAP-050, GAP-063, and GAP-065 inherit both changes through their dependency on it.")
L.append("- D-19 (2026-09-05) signed off `egui_tiles` 0.10 as the docking crate, closing the\n  last open §2.9 question. It enters a member manifest under GAP-075.")
L.append("- Plan 10 (TOGAF ADM, 2026-09-04) ran the first compliance assessment against the\n  code and added GAP-081 to GAP-083: automating the five mechanical contract checks,\n  proving no `todo!()` is reachable, and making requirement identifiers traceable.")
L.append('- D-34\'s licence gate was **run for the first time on 2026-09-07**, in the licensing\n  review that followed the decision, and failed twice, both on the `deny.toml` comment\'s\n  claim that `OpenSSL` had been the only entry that mattered. `epaint_default_fonts`,\n  which `gungnir-app` embeds, declares the SIL Open Font License and the Ubuntu Font\n  Licence for its font data, neither on the allow-list; and `webpki-root-certs`\n  (CDLA-Permissive-2.0) sat in the wasm32 slice of the graph that cargo-deny evaluates\n  by default and no binary builds. The first is admitted by a `[[licenses.exceptions]]`\n  scoped to that one crate, with the reasoning in `deny.toml`; the second is answered\n  by restricting `[graph] targets` to the two release targets. The same review found\n  that nothing shipped the notices the permissive licenses require to accompany a\n  binary: `about.toml` and `cargo about` now generate `THIRD-PARTY-NOTICES.md` in the\n  release, the node image carries the licence files, `ci.yml` runs the licence check on\n  every pull request, `gungnir-fuzz` (outside the workspace, so unable to inherit) now\n  states the licence, and `testdata/oracles`, `tracks`, `assets` and `scientific` gained\n  the `SOURCE.md` that `NOTICE` already said they had. Two further failures were the\n  gate\'s own shape rather than a third-party licence: cargo-deny holds the workspace\'s\n  crates to the same allow-list, and `AGPL-3.0-or-later` is deliberately not on it (a\n  global entry would admit an outside AGPL crate that CLA.md section 4 cannot accept),\n  so the fifty members are admitted by name in `[[licenses.exceptions]]`; and the\n  wildcard ban reads a versionless `path` dependency as a wildcard, so every\n  intra-workspace edge now carries `version = "0.1.0"`, which crates.io requires anyway.\n  With those, `cargo deny check licenses bans sources` passes. Every `Cargo.toml` now\n  carries the same three-line header as the source files (fifty-two manifests, the root\n  and `gungnir-fuzz` included). Consistency is one reason; the other is that cargo-about\n  looks for the licence expression *in the manifest text*, and a manifest that inherits\n  it through `license.workspace = true` has none, which sends cargo-about 0.9.2 down a\n  synthesised-manifest path with an offset bug that panics on any manifest containing a\n  non-ASCII character -- forty-two of them do, from the `§` citations. The header\'s SPDX\n  line is the text it finds. A second cargo-about defect, in its `LicenseRef` handling,\n  is recorded in `about.toml` with the template\'s workaround. **`cargo deny check\n  advisories`, which `release.yml` also runs, does not**: `vtkio` 0.6.3 pins `quick-xml`\n  0.22 and `lz4_flex` 0.7, both with open RUSTSEC vulnerabilities; the Linux\n  accessibility path under `eframe` (`accesskit_unix`, `zbus_xml`) carries `quick-xml`\n  0.30 with the same two; and six crates are flagged unmaintained (`ansi_term`,\n  `cgmath`, `instant`, `paste`, `rustls-pemfile`, `ttf-parser`). None is a licensing\n  matter; it is recorded here because the first tag will otherwise discover it, and it\n  is a dependency decision under §2.9, not something the licensing review could take.\n  **Acted on the same day for the unmaintained six**, after weighing forking against\n  replacing: `rustls-pemfile`, the only one of the six that was a direct dependency and\n  the only one parsing input on the mutual TLS path, was replaced by the PEM reader in\n  `rustls::pki_types::pem` (rustls\'s own re-exported type crate, so the graph lost a\n  crate, gained none, and no manifest names anything new); `ansi_term` (dev-only) and `paste` (a proc-macro, compile-time\n  only) are ignored in `deny.toml` with dated reasons; `instant` left the same day\n  with three-d\'s default `window` feature, which the viewport never used (it draws into\n  eframe\'s glow context; the feature carried a second winit, 0.28, and glutin beneath it);\n  `cgmath` is three-d\'s own math type, still a dependency of three-d 0.19, and stays\n  until three-d drops it or is replaced (0.19 is ruled out by its move to glow 0.17 and\n  egui 0.34 against eframe 0.29\'s glow 0.14); `ttf-parser` waits on egui\'s `ab_glyph`\n  moving to its successor. **The owner decided on 2026-09-07 to ignore both** rather\n  than hold releases on an upstream with no date: `cgmath` is pure math on data this\n  program computes, and `ttf-parser` parses only the four fonts embedded at build time\n  (nothing here builds a `FontDefinitions` or reads a font from disk), so neither sees\n  untrusted input, and neither has an upstream path. Both entries in `deny.toml` carry\n  that reason, and the second carries a condition: loading a user-supplied font would\n  need it removed first. Forking was rejected: the graph refuses git\n  dependencies, so a fork means vendoring, and owning a font parser with no upstream is\n  a larger accreditation question than the advisory it would close.\n  **The three vulnerabilities followed the same day.** `vtkio` 0.6.3\'s XML reader\n  (quick-xml 0.22: RUSTSEC-2026-0194 and -0195) and its appended-data codecs (lz4_flex\n  0.7: RUSTSEC-2026-0041) have no patched upstream, since even the 0.7.0 candidates pin\n  quick-xml 0.36 against a fix in 0.41, and a VTK file is operator-supplied input on the\n  node. Both features are compiled out: only legacy `.vtk` loads, `gungnir-data` refuses\n  an XML extension naming the reason, a test holds that wording, and the workspace\n  `Cargo.toml` says what restores them. GAP-023\'s "legacy and XML" therefore narrowed to\n  legacy on 2026-09-07; the XML half is owed to a vtkio release, not to this project.\n  The remaining quick-xml (0.30, under `accesskit_unix`, the Linux AT-SPI bridge) exists\n  only in `gungnir-app` compiled for Linux, which no release builds; its two advisory ids\n  are ignored in `deny.toml` with that reason and with the caveat that an id-level\n  ignore would also mask a new pre-0.41 quick-xml, which the ignore\'s own match report\n  is the check for. With those two ignores, `cargo deny check` passes all four checks\n  for the first time.')
L.append("- D-34's rows in both tables above were **lost on main on 2026-09-07** by commit\n  `0ac4d4b` (GAP-057), whose copy of this file predated the decision; the same commit\n  dropped D-35 to D-38, which the renumbering commit `34796a6` had just added. The\n  rebase of the licensing review restored D-34, since it is that review's subject.\n  **Restored 2026-09-07** by commit `a6bc70f`, which came after this paragraph was\n  first written and left the paragraph itself saying they were still missing;\n  corrected 2026-09-08 on finding the two disagreed. They belong to the theme tranche\n  that owns them; `docs/ux/design-system.md` also cites them.")
L.append("- D-34's one engineering item is **closed 2026-09-07**: `gungnir-app` displays the\n  Appropriate Legal Notices as PN-21, so the section 7(b) interface requirement now\n  reaches a derivative under AGPL section 5(d). PN-21 is the twenty-first panel and is\n  in `docs/ux/information-architecture.md` §3 and `ux-to-code-map.md` §1; it is in no\n  role's layout by design, and two tests hold that open.")
L.append("- D-40, D-41 and D-42 (2026-09-08) each un-blocked an owner-only judgement call the\n  register had been carrying: the ML inference runtime GAP-077 deferred (`ort`, native\n  dependency accepted, `download-binaries` refused for its third-party-CDN telemetry\n  risk), real-world CRS support for DEM and point-cloud files GAP-023 and GAP-098 both\n  needed (`proj`, full projection support), and the cloud KMS crates GAP-084's\n  `ManagedService` profile needed (`aws-sdk-kms` and `azure_security_keyvault_keys`).\n  D-40 and D-41 are decisions only: neither is yet recorded in\n  `agentic-coding-standards.md` §2.9 and neither is built. **D-42 is recorded and built**,\n  2026-09-08: §2.9 carries its crate table (with the correction that\n  `azure_security_keyvault_keys` is 1.0.1 and not the pre-1.0 version the decision recorded,\n  and with `aws-config` added for the credential chain the service crate does not carry), and\n  DN-22 amendment 5 designs the profile the crates serve. STANAG 4676 (GAP-063, GAP-064) was walked the same session\n  and the owner declined to purchase the paywalled specification, leaving that gap's\n  status unchanged.")
(OUT / "decisions-needed.md").write_text(rel("\n".join(L)) + "\n", encoding="utf-8", newline="\n")

print("gaps", len(G), "mission", n_m, "technical", n_t)
print("targets", Counter(g["target"] for g in G))
print("layers", Counter(g["layer"] for g in G if g["type"] == "Technical"))
print("design", dcount, "impl", icount)
