//! Differential test for the verification-capability-table.md §1 row
//! "`filters` | Linear Kalman Filter".
//!
//! Oracle `filterpy.kalman.KalmanFilter`. Pass criterion: **state < 1e-6; covariance
//! Frobenius difference < 1e-6**, over the same measurement sequence.
//!
//! The fixture records the state and covariance after *every* predict and after every
//! update, and this test checks all of them. Comparing only the final state would let
//! a filter reach the right answer by a wrong path -- two compensating errors in the
//! gain and the covariance update do exactly that -- and would also not say which half
//! of the cycle was wrong when it failed.
//!
//! `testdata/oracles/filters/linear_kalman.json` is regenerated by
//! `testdata/oracles/tools/gen_kalman_fixtures.py`. MATLAB's `trackingKF` is named by
//! the row and was **not** run: MATLAB is not installed, and
//! `testdata/oracles/README.md` records that.

use gungnir_core::ConstantVelocity;
use gungnir_filters::{Filter, KalmanFilter};
use nalgebra::{SMatrix, SVector};

/// The row's two tolerances, verbatim.
const TOL_STATE: f64 = 1e-6;
const TOL_COV_FROBENIUS: f64 = 1e-6;

#[derive(serde::Deserialize)]
struct Snapshot {
    x: Vec<f64>,
    p: Vec<Vec<f64>>,
}

#[derive(serde::Deserialize)]
struct Step {
    z: Vec<f64>,
    after_predict: Snapshot,
    after_update: Snapshot,
}

#[derive(serde::Deserialize)]
struct Case {
    name: String,
    dt: f64,
    sigma_a_sq: f64,
    r_diag: Vec<f64>,
    p0_diag: Vec<f64>,
    x0: Vec<f64>,
    steps: Vec<Step>,
}

#[derive(serde::Deserialize)]
struct Fixture {
    row: String,
    oracle: String,
    cases: Vec<Case>,
}

fn load() -> Fixture {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../testdata/oracles/filters/linear_kalman.json"
    );
    let raw = std::fs::read_to_string(path)
        .expect("oracle fixture present; see testdata/oracles/README.md");
    serde_json::from_str(&raw).expect("oracle fixture parses")
}

/// Position-only measurement matrix: the first three states.
fn measurement_matrix() -> SMatrix<f64, 3, 6> {
    let mut h = SMatrix::<f64, 3, 6>::zeros();
    for axis in 0..3 {
        h[(axis, axis)] = 1.0;
    }
    h
}

fn diagonal<const N: usize>(values: &[f64]) -> SMatrix<f64, N, N> {
    assert_eq!(values.len(), N, "fixture diagonal has the wrong length");
    let mut m = SMatrix::<f64, N, N>::zeros();
    for (i, v) in values.iter().enumerate() {
        m[(i, i)] = *v;
    }
    m
}

fn vector<const N: usize>(values: &[f64]) -> SVector<f64, N> {
    assert_eq!(values.len(), N, "fixture vector has the wrong length");
    SVector::<f64, N>::from_iterator(values.iter().copied())
}

fn oracle_covariance(rows: &[Vec<f64>]) -> SMatrix<f64, 6, 6> {
    assert_eq!(rows.len(), 6, "fixture covariance is not 6x6");
    SMatrix::<f64, 6, 6>::from_fn(|i, j| rows[i][j])
}

/// Largest absolute state difference, and the index it is at.
fn worst_state(a: &SVector<f64, 6>, b: &SVector<f64, 6>) -> (f64, usize) {
    let mut worst = (0.0_f64, 0);
    for i in 0..6 {
        let d = (a[i] - b[i]).abs();
        if d > worst.0 {
            worst = (d, i);
        }
    }
    worst
}

/// Frobenius norm of the covariance difference: the row's stated measure.
fn frobenius(a: &SMatrix<f64, 6, 6>, b: &SMatrix<f64, 6, 6>) -> f64 {
    (a - b).norm()
}

struct Margins {
    state: f64,
    covariance: f64,
    where_worst: String,
}

/// Replay one case and return the worst margins seen anywhere in it.
fn replay(case: &Case) -> Margins {
    let mut kf: KalmanFilter<ConstantVelocity, 6, 3> = KalmanFilter::new(
        vector::<6>(&case.x0),
        diagonal::<6>(&case.p0_diag),
        ConstantVelocity {
            sigma_a_sq: case.sigma_a_sq,
        },
        measurement_matrix(),
        diagonal::<3>(&case.r_diag),
    );

    let mut margins = Margins {
        state: 0.0,
        covariance: 0.0,
        where_worst: String::new(),
    };
    let mut record =
        |phase: &str, step: usize, kf: &KalmanFilter<ConstantVelocity, 6, 3>, want: &Snapshot| {
            let expected_x = vector::<6>(&want.x);
            let expected_p = oracle_covariance(&want.p);
            let (ds, idx) = worst_state(kf.state(), &expected_x);
            let dp = frobenius(kf.covariance(), &expected_p);

            assert!(
                kf.state().iter().all(|v| v.is_finite()),
                "{}: non-finite state after {phase} at step {step}",
                case.name
            );
            assert!(
                ds < TOL_STATE,
                "{}: state[{idx}] after {phase} at step {step} differs by {ds:e} \
             ({} vs oracle {}), tolerance {TOL_STATE:e}",
                case.name,
                kf.state()[idx],
                expected_x[idx]
            );
            assert!(
                dp < TOL_COV_FROBENIUS,
                "{}: covariance after {phase} at step {step} differs by {dp:e} in \
             Frobenius norm, tolerance {TOL_COV_FROBENIUS:e}",
                case.name
            );
            if ds > margins.state {
                margins.state = ds;
                margins.where_worst = format!("{} after {phase} at step {step}", case.name);
            }
            if dp > margins.covariance {
                margins.covariance = dp;
            }
        };

    for (i, step) in case.steps.iter().enumerate() {
        kf.predict(case.dt);
        record("predict", i, &kf, &step.after_predict);
        kf.update(&vector::<3>(&step.z));
        record("update", i, &kf, &step.after_update);
    }
    assert_eq!(
        kf.rejected_updates(),
        0,
        "{}: the filter skipped an update, so the comparison above is not of the \
         same computation",
        case.name
    );
    margins
}

#[test]
fn fixture_is_the_expected_row() {
    let f = load();
    assert_eq!(f.row, "Linear Kalman Filter");
    assert_eq!(f.oracle, "filterpy.kalman.KalmanFilter");
    assert!(!f.cases.is_empty());
    assert!(
        f.cases.iter().all(|c| !c.steps.is_empty()),
        "a case with no steps proves nothing"
    );
}

#[test]
fn linear_kalman_matches_filterpy() {
    let fixture = load();
    let mut worst_state = 0.0_f64;
    let mut worst_cov = 0.0_f64;
    let mut worst_where = String::new();
    let mut steps = 0;

    for case in &fixture.cases {
        let m = replay(case);
        steps += case.steps.len();
        if m.state > worst_state {
            worst_state = m.state;
            worst_where = m.where_worst;
        }
        worst_cov = worst_cov.max(m.covariance);
    }

    println!(
        "linear KF: {steps} steps over {} cases; worst state {worst_state:e} \
         (tolerance {TOL_STATE:e}) at {worst_where}; worst covariance Frobenius \
         {worst_cov:e} (tolerance {TOL_COV_FROBENIUS:e})",
        fixture.cases.len()
    );
}

/// Every covariance the filter produces along the fixture must be a valid covariance,
/// not merely close to the oracle's. Agreement with a reference that itself drifted
/// indefinite would be agreement on a wrong answer.
#[test]
fn every_covariance_along_the_fixture_is_psd() {
    let fixture = load();
    for case in &fixture.cases {
        let mut kf: KalmanFilter<ConstantVelocity, 6, 3> = KalmanFilter::new(
            vector::<6>(&case.x0),
            diagonal::<6>(&case.p0_diag),
            ConstantVelocity {
                sigma_a_sq: case.sigma_a_sq,
            },
            measurement_matrix(),
            diagonal::<3>(&case.r_diag),
        );
        for (i, step) in case.steps.iter().enumerate() {
            kf.predict(case.dt);
            kf.update(&vector::<3>(&step.z));
            let p = kf.covariance();
            let asymmetry = (p - p.transpose()).abs().max();
            assert!(
                asymmetry < 1e-9,
                "{}: covariance asymmetric by {asymmetry:e} at step {i}",
                case.name
            );
            let mut shifted = *p;
            for d in 0..6 {
                shifted[(d, d)] += 1e-12;
            }
            assert!(
                shifted.cholesky().is_some(),
                "{}: covariance not positive semi-definite at step {i}",
                case.name
            );
        }
    }
}
