Option Explicit

' Executes gungnir-uaf-import.vbs (generated by export_ea_script.py) against a
' hand-written mock of the EA Automation object model, via cscript.exe outside
' of EA. This is NOT a substitute for a real EA import: it cannot tell you
' whether Connectors.AddNew really persists a visible connector, whether a
' stereotype name binds to UAF iconography, or anything else about EA's actual
' behaviour. What it does confirm, cheaply and repeatably, is that the generated
' script -- including its CSV parsing -- is syntactically valid VBScript and
' that its control flow runs to completion without a VBScript compilation or
' runtime error, exactly the class of bug that would otherwise only surface
' after a slow paste-into-EA-and-run cycle.
'
' Usage:
'   cscript.exe //Nologo test_ea_script_mock.vbs [path-to-generated-vbs] [data-dir]
' Both default to ..\exports relative to this file (where export_ea_script.py
' writes the driver and its four CSV files together).

Dim nextId, allObjectsByID
nextId = 1
Set allObjectsByID = CreateObject("Scripting.Dictionary")

Class MockObj
  Public Name
  Public Stereotype
  Public Notes
  Public SupplierID
  Public ElementID
  Public ConnectorID
  Private childrenByKind

  Public Sub Class_Initialize()
    ElementID = nextId
    ConnectorID = nextId
    allObjectsByID.Add nextId, Me
    nextId = nextId + 1
    Set childrenByKind = CreateObject("Scripting.Dictionary")
  End Sub

  Public Function GetCollection(kind)
    If Not childrenByKind.Exists(kind) Then
      childrenByKind.Add kind, New MockCollection
    End If
    Set GetCollection = childrenByKind.Item(kind)
  End Function

  Public Property Get Models()
    Set Models = GetCollection("Models")
  End Property
  Public Property Get Packages()
    Set Packages = GetCollection("Packages")
  End Property
  Public Property Get Elements()
    Set Elements = GetCollection("Elements")
  End Property
  Public Property Get Connectors()
    Set Connectors = GetCollection("Connectors")
  End Property
  Public Property Get TaggedValues()
    Set TaggedValues = GetCollection("TaggedValues")
  End Property

  Public Function Update()
    Update = True
  End Function
  Public Function Refresh()
    Refresh = True
  End Function
End Class

Class MockCollection
  Private items
  Public Sub Class_Initialize()
    Set items = CreateObject("Scripting.Dictionary")
  End Sub
  Public Function AddNew(nm, typ)
    Dim o
    Set o = New MockObj
    o.Name = nm
    items.Add items.Count, o
    Set AddNew = o
  End Function
  Public Property Get Count()
    Count = items.Count
  End Property
  Public Function GetAt(i)
    Set GetAt = items.Item(i)
  End Function
  Public Function Refresh()
    Refresh = True
  End Function
End Class

Class MockRepository
  Public EnableCache
  Public EnableUIUpdates
  Private allElements

  Public Sub Class_Initialize()
    Set allElements = CreateObject("Scripting.Dictionary")
  End Sub

  Public Property Get Models()
    If Not allElements.Exists("__models__") Then
      allElements.Add "__models__", New MockCollection
    End If
    Set Models = allElements.Item("__models__")
  End Property

  Public Function GetElementByID(id)
    ' Real lookup, not a fabricated stand-in: proves a value set on an element
    ' (e.g. Notes) earlier in the script is still there when read back later,
    ' the way the driver's element-tags and relationships passes both do.
    Set GetElementByID = allObjectsByID.Item(id)
  End Function

  Public Function GetConnectorByID(id)
    Set GetConnectorByID = allObjectsByID.Item(id)
  End Function
End Class

Class MockSession
  Public Sub Output(msg)
    WScript.Echo "[OUTPUT] " & msg
  End Sub
End Class

Dim Repository, Session
Set Repository = New MockRepository
Set Session = New MockSession

Dim scriptDir, targetPath, dataDir, fso
Set fso = CreateObject("Scripting.FileSystemObject")
scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)
If WScript.Arguments.Count >= 1 Then
  targetPath = WScript.Arguments(0)
Else
  targetPath = scriptDir & "\..\exports\gungnir-uaf-import.vbs"
End If
If WScript.Arguments.Count >= 2 Then
  dataDir = WScript.Arguments(1)
Else
  dataDir = scriptDir & "\..\exports"
End If

Dim f, rawLines, filteredLines, i, keep, line, scriptText
Set f = fso.OpenTextFile(targetPath, 1, False, 0)  ' 0 = ASCII; the generator writes strict ASCII
rawLines = Split(f.ReadAll(), vbLf)
f.Close

' Strip the trailing MsgBox line (would pop a blocking GUI dialog under
' cscript.exe) and point DATA_DIR at the real exports folder instead of the
' generator's edit-this-yourself placeholder.
ReDim filteredLines(UBound(rawLines))
keep = 0
For i = 0 To UBound(rawLines)
  line = rawLines(i)
  If Left(Trim(line), 6) = "MsgBox" Then
    ' drop it
  ElseIf Left(Trim(line), 16) = "Const DATA_DIR =" Then
    filteredLines(keep) = "Const DATA_DIR = """ & dataDir & """"
    keep = keep + 1
  Else
    filteredLines(keep) = line
    keep = keep + 1
  End If
Next
ReDim Preserve filteredLines(keep - 1)
scriptText = Join(filteredLines, vbLf)

ExecuteGlobal scriptText

WScript.Echo "test_ea_script_mock: " & targetPath & " (data: " & dataDir & ") executed to completion without error"

' End-to-end check of the one thing that already broke once: a real non-ASCII
' character surviving CSV write -> CSV parse -> \uXXXX decode -> el.Notes,
' checked by length delta and AscW on the actual string (not by eyeballing
' console output, which silently drops characters cscript's codepage can't
' render -- that is exactly what produced a false "it's broken" reading during
' development here).
Dim checkId, checkEl, notesLen, foundNonAscii, k
checkId = "RS-analytics"  ' known to carry the section sign in its description
If elementIds.Exists(checkId) Then
  Set checkEl = Repository.GetElementByID(elementIds.Item(checkId))
  foundNonAscii = False
  For k = 1 To Len(checkEl.Notes)
    If AscW(Mid(checkEl.Notes, k, 1)) = 167 Then
      foundNonAscii = True
      Exit For
    End If
  Next
  If foundNonAscii Then
    WScript.Echo "UNICODE CHECK: PASS -- " & checkId & "'s Notes contains a real section-sign character (U+00A7), not a § escape or a stray backslash"
  Else
    WScript.Echo "UNICODE CHECK: FAIL -- " & checkId & "'s Notes does not contain U+00A7. Notes length=" & Len(checkEl.Notes)
  End If
Else
  WScript.Echo "UNICODE CHECK: SKIPPED -- " & checkId & " not found (registry data may have changed)"
End If
