Option Explicit

' Executes gungnir-uaf-import.vbs (generated by export_ea_script.py) against a
' hand-written mock of the EA Automation object model, via cscript.exe outside
' of EA. This is NOT a substitute for a real EA import: it cannot tell you
' whether Connectors.AddNew really persists a visible connector, whether a
' stereotype name binds to UAF iconography, or anything else about EA's actual
' behaviour. What it does confirm, cheaply and repeatably, is that the generated
' script is syntactically valid VBScript and that its control flow (loops, the
' element-id Dictionary, every AddNew/Update/Refresh call) runs to completion
' without a VBScript compilation or runtime error -- exactly the class of bug
' that would otherwise only surface after a slow paste-into-EA-and-run cycle.
'
' Usage:
'   cscript.exe //Nologo test_ea_script_mock.vbs [path-to-generated-vbs]
' Defaults to ..\exports\gungnir-uaf-import.vbs relative to this file.

Dim nextId
nextId = 1

Class MockObj
  Public Name
  Public Stereotype
  Public Notes
  Public SupplierID
  Public ElementID
  Private childrenByKind

  Public Sub Class_Initialize()
    ElementID = nextId
    nextId = nextId + 1
    Set childrenByKind = CreateObject("Scripting.Dictionary")
  End Sub

  Public Function GetCollection(kind)
    If Not childrenByKind.Exists(kind) Then
      childrenByKind.Add kind, New MockCollection
    End If
    Set GetCollection = childrenByKind.Item(kind)
  End Function

  Public Property Get Models()
    Set Models = GetCollection("Models")
  End Property
  Public Property Get Packages()
    Set Packages = GetCollection("Packages")
  End Property
  Public Property Get Elements()
    Set Elements = GetCollection("Elements")
  End Property
  Public Property Get Connectors()
    Set Connectors = GetCollection("Connectors")
  End Property
  Public Property Get TaggedValues()
    Set TaggedValues = GetCollection("TaggedValues")
  End Property

  Public Function Update()
    Update = True
  End Function
  Public Function Refresh()
    Refresh = True
  End Function
End Class

Class MockCollection
  Private items
  Public Sub Class_Initialize()
    Set items = CreateObject("Scripting.Dictionary")
  End Sub
  Public Function AddNew(nm, typ)
    Dim o
    Set o = New MockObj
    o.Name = nm
    items.Add items.Count, o
    Set AddNew = o
  End Function
  Public Property Get Count()
    Count = items.Count
  End Property
  Public Function GetAt(i)
    Set GetAt = items.Item(i)
  End Function
  Public Function Refresh()
    Refresh = True
  End Function
End Class

Class MockRepository
  Public EnableCache
  Public EnableUIUpdates
  Private allElements

  Public Sub Class_Initialize()
    Set allElements = CreateObject("Scripting.Dictionary")
  End Sub

  Public Property Get Models()
    If Not allElements.Exists("__models__") Then
      allElements.Add "__models__", New MockCollection
    End If
    Set Models = allElements.Item("__models__")
  End Property

  Public Function GetElementByID(id)
    Dim o
    Set o = New MockObj
    o.ElementID = id
    Set GetElementByID = o
  End Function
End Class

Class MockSession
  Public Sub Output(msg)
    WScript.Echo "[OUTPUT] " & msg
  End Sub
End Class

Dim Repository, Session
Set Repository = New MockRepository
Set Session = New MockSession

Dim targetPath, fso
Set fso = CreateObject("Scripting.FileSystemObject")
If WScript.Arguments.Count >= 1 Then
  targetPath = WScript.Arguments(0)
Else
  targetPath = fso.GetParentFolderName(WScript.ScriptFullName) & "\..\exports\gungnir-uaf-import.vbs"
End If

Dim f, rawLines, filteredLines, i, keep, scriptText
Set f = fso.OpenTextFile(targetPath, 1, False, 0)  ' 0 = ASCII; the generator writes strict ASCII
rawLines = Split(f.ReadAll(), vbLf)
f.Close

' Strip the trailing MsgBox line -- it would pop a blocking GUI dialog under
' cscript.exe. Everything before it still executes.
ReDim filteredLines(UBound(rawLines))
keep = 0
For i = 0 To UBound(rawLines)
  If Left(Trim(rawLines(i)), 6) <> "MsgBox" Then
    filteredLines(keep) = rawLines(i)
    keep = keep + 1
  End If
Next
ReDim Preserve filteredLines(keep - 1)
scriptText = Join(filteredLines, vbLf)

ExecuteGlobal scriptText

WScript.Echo "test_ea_script_mock: " & targetPath & " executed to completion without error"
