//! Differential test for the verification-capability-table.md §1 row
//! "Motion models: CV, CA, CT".
//!
//! Oracles: `filterpy` (closed form), Stone Soup (`KnownTurnRate`), and scipy
//! (`expm` / Van Loan). Pass criterion: exact match, ~1e-10, element-wise on `F`
//! and `Q` for the same `dt`.
//!
//! The fixture records every oracle that produced a finite answer for a case, and
//! this test asserts against **all** of them at the row's tolerance rather than
//! against one favourite. Where an oracle is absent from a case, the fixture's
//! `degenerate_oracles` list says which one and why; `oracle_coverage_is_declared`
//! below fails if a case ever silently loses its whole oracle set.
//!
//! The fixture is `testdata/oracles/core/motion_models.json`, regenerated by
//! `testdata/oracles/tools/gen_motion_model_fixtures.py`. MATLAB's `initcvkf`,
//! `initcakf`, and `initctekf` are named by the capability-table row and are **not**
//! run: MATLAB is not installed on this machine, and `testdata/oracles/README.md`
//! records that the row is gated on the Python and scipy columns alone.

use gungnir_core::{ConstantAcceleration, ConstantVelocity, CoordinatedTurn, MotionModel};
use nalgebra::{DMatrix, SMatrix};
use std::collections::BTreeMap;

/// The capability-table tolerance for this row.
const TOL: f64 = 1e-10;

#[derive(serde::Deserialize)]
struct OracleMatrices {
    #[serde(default)]
    f: Option<Vec<Vec<f64>>>,
    #[serde(default)]
    q: Option<Vec<Vec<f64>>>,
}

#[derive(serde::Deserialize)]
struct Case {
    model: String,
    dim: usize,
    dt: f64,
    #[serde(default)]
    sigma_a_sq: Option<f64>,
    #[serde(default)]
    sigma_j_sq: Option<f64>,
    #[serde(default)]
    omega: Option<f64>,
    oracles: BTreeMap<String, OracleMatrices>,
}

#[derive(serde::Deserialize)]
struct DegenerateOracle {
    dt: f64,
    omega: f64,
    oracle: String,
}

#[derive(serde::Deserialize)]
struct Fixture {
    row: String,
    cases: Vec<Case>,
    degenerate_oracles: Vec<DegenerateOracle>,
    cross_oracle_worst_disagreement: f64,
}

fn load() -> Fixture {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../testdata/oracles/core/motion_models.json"
    );
    let raw = std::fs::read_to_string(path)
        .expect("oracle fixture present; see testdata/oracles/README.md");
    serde_json::from_str(&raw).expect("oracle fixture parses")
}

fn to_dmatrix(rows: &[Vec<f64>]) -> DMatrix<f64> {
    let n = rows.len();
    let m = rows.first().map_or(0, Vec::len);
    DMatrix::from_fn(n, m, |i, j| rows[i][j])
}

fn from_smatrix<const N: usize>(m: &SMatrix<f64, N, N>) -> DMatrix<f64> {
    DMatrix::from_fn(N, N, |i, j| m[(i, j)])
}

/// Worst element-wise disagreement, and where it is.
fn worst_element(a: &DMatrix<f64>, b: &DMatrix<f64>) -> (f64, usize, usize) {
    let mut worst = (0.0_f64, 0, 0);
    for i in 0..a.nrows() {
        for j in 0..a.ncols() {
            let d = (a[(i, j)] - b[(i, j)]).abs();
            if d > worst.0 {
                worst = (d, i, j);
            }
        }
    }
    worst
}

/// Compare one matrix against one oracle, panicking with the offending element.
fn assert_matches(
    got: &DMatrix<f64>,
    expected: &DMatrix<f64>,
    case: &Case,
    oracle: &str,
    matrix: &str,
    running_worst: &mut f64,
) {
    assert_eq!(
        (got.nrows(), got.ncols()),
        (expected.nrows(), expected.ncols()),
        "{} {matrix} shape differs from oracle {oracle}",
        case.model
    );
    for v in got.iter() {
        assert!(
            v.is_finite(),
            "{} {matrix} at dt={} contains a non-finite element",
            case.model,
            case.dt
        );
    }
    let (d, i, j) = worst_element(got, expected);
    if d > *running_worst {
        *running_worst = d;
    }
    assert!(
        d < TOL,
        "{} {matrix}[{i}][{j}] at dt={} omega={:?} density={:?}: {:e} vs oracle {oracle} {:e}, \
         difference {d:e} exceeds {TOL:e}",
        case.model,
        case.dt,
        case.omega,
        case.sigma_a_sq.or(case.sigma_j_sq),
        got[(i, j)],
        expected[(i, j)],
    );
}

/// Build `F` and `Q` for a case from the crate under test.
fn evaluate(case: &Case) -> (DMatrix<f64>, DMatrix<f64>) {
    match case.model.as_str() {
        "ConstantVelocity" => {
            let m = ConstantVelocity {
                sigma_a_sq: case.sigma_a_sq.expect("CV case carries sigma_a_sq"),
            };
            (from_smatrix(&m.f(case.dt)), from_smatrix(&m.q(case.dt)))
        }
        "ConstantAcceleration" => {
            let m = ConstantAcceleration {
                sigma_j_sq: case.sigma_j_sq.expect("CA case carries sigma_j_sq"),
            };
            (from_smatrix(&m.f(case.dt)), from_smatrix(&m.q(case.dt)))
        }
        "CoordinatedTurn" => {
            let m = CoordinatedTurn {
                omega: case.omega.expect("CT case carries omega"),
                sigma_a_sq: case.sigma_a_sq.expect("CT case carries sigma_a_sq"),
            };
            (from_smatrix(&m.f(case.dt)), from_smatrix(&m.q(case.dt)))
        }
        other => panic!("fixture names an unknown model {other}"),
    }
}

#[test]
fn fixture_is_the_expected_row() {
    let fixture = load();
    assert_eq!(fixture.row, "Motion models: CV, CA, CT");
    assert!(!fixture.cases.is_empty());
    assert!(
        fixture.cross_oracle_worst_disagreement < TOL,
        "the oracles disagree with each other by {:e}, which is at or beyond the row's \
         own tolerance of {TOL:e}; the fixture cannot adjudicate this row until that is \
         understood",
        fixture.cross_oracle_worst_disagreement
    );
}

/// Every case must be adjudicated by at least one oracle per matrix, and any oracle
/// dropped from a case must appear in `degenerate_oracles`. This is what stops a
/// silently-empty oracle set from reading as a pass.
#[test]
fn oracle_coverage_is_declared() {
    let fixture = load();
    for case in &fixture.cases {
        let has_f = case.oracles.values().any(|o| o.f.is_some());
        let has_q = case.oracles.values().any(|o| o.q.is_some());
        assert!(
            has_f && has_q,
            "{} at dt={} has no oracle for {}",
            case.model,
            case.dt,
            if has_f { "Q" } else { "F" }
        );
    }
    for dropped in &fixture.degenerate_oracles {
        assert!(
            !dropped.oracle.is_empty(),
            "a dropped oracle at dt={} omega={} is unnamed",
            dropped.dt,
            dropped.omega
        );
    }
    // Stone Soup's KnownTurnRate divides by the turn rate; the omega == 0 cases are
    // the ones it cannot answer. If that list ever empties, the generator stopped
    // exercising the degenerate turn rate and this test should be revisited.
    assert!(
        fixture
            .degenerate_oracles
            .iter()
            .any(|d| d.omega == 0.0 && d.oracle == "stonesoup"),
        "expected the omega == 0 coordinated-turn cases to be recorded as beyond \
         Stone Soup's KnownTurnRate"
    );
}

#[test]
fn motion_models_match_every_oracle() {
    let fixture = load();
    let mut worst_by_model: BTreeMap<String, f64> = BTreeMap::new();
    let mut checked = 0_usize;

    for case in &fixture.cases {
        let (f, q) = evaluate(case);
        assert_eq!(f.nrows(), case.dim, "{} F has the declared dim", case.model);

        for (oracle, matrices) in &case.oracles {
            let key = format!("{} vs {oracle}", case.model);
            let entry = worst_by_model.entry(key).or_insert(0.0);
            if let Some(rows) = &matrices.f {
                assert_matches(&f, &to_dmatrix(rows), case, oracle, "F", entry);
                checked += 1;
            }
            if let Some(rows) = &matrices.q {
                assert_matches(&q, &to_dmatrix(rows), case, oracle, "Q", entry);
                checked += 1;
            }
        }
    }

    assert!(checked > 0, "no oracle comparison ran");
    println!(
        "motion models: {checked} oracle comparisons across {} cases",
        fixture.cases.len()
    );
    for (model, worst) in &worst_by_model {
        println!("  {model}: worst element-wise disagreement {worst:e} (tolerance {TOL:e})");
    }
}

/// `Q` must be a valid covariance for every case in the fixture, not merely close to
/// the oracle: agentic-coding-standards.md §2.1 requires PSD, and a `Q` that is not
/// PSD poisons every covariance downstream of it.
#[test]
fn every_fixture_q_is_psd() {
    let fixture = load();
    for case in &fixture.cases {
        let (_, q) = evaluate(case);
        let asymmetry = (&q - &q.transpose()).abs().max();
        assert!(
            asymmetry < 1e-9,
            "{} Q at dt={} is asymmetric by {asymmetry:e}",
            case.model,
            case.dt
        );
        let mut shifted = q.clone();
        for i in 0..shifted.nrows() {
            shifted[(i, i)] += 1e-12;
        }
        assert!(
            shifted.cholesky().is_some(),
            "{} Q at dt={} is not positive semi-definite",
            case.model,
            case.dt
        );
    }
}
